name: Main-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Runs on PR opened, updated, or reopened

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the OS to run the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from the repository

     # - name: Set up JDK 11
     #   uses: actions/setup-java@v2
     #   with:
     #     java-version: '11'  # Set the desired JDK version

      - name: Run a dummy task
        run: |
          echo "Running dummy task..."
          # Here you can add actual build commands later

      - name: Run tests
        run: |
          echo "Running tests..."
          # You can replace this with actual test commands later

      - name: Dummy step for future integration
        run: |
          echo "This step is a placeholder for future tasks."
